ScrumTool/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Common.CommandTrees;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using ScrumTool.Database;
using ScrumTool.Objects;

namespace ScrumTool.Controllers
{
    [Authorize]
    public class ProjectController : BaseController
    {
        // GET: Project
        public ActionResult Index()
        {
            using (var entities = new ScrumDB())
            {
                try
                {
                    return View(entities.Projects.ToList());
                }
                catch (Exception e)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, e.Message);
                }
                
            }
        }

        // GET: Project/Details/5
        public ActionResult Details(int id)
        {
            //TODO: add error handling here
            using (var entities = new ScrumDB())
            {
                var proj = entities.Projects.Include("Teams").Include("Users").FirstOrDefault(p => p.ID == id);
                if (proj == null)
                {
                    ViewBag.ErrorMessage = string.Format("Project id {0} was not found.", id);
                    return RedirectToAction("Index");
                }
                var allBacklogItems = entities.BacklogItems.Where(b => b.ProjectID == id);
                ViewBag.BacklogItems = allBacklogItems;

                // TEAM MEMBERS
                var teamMembers = new Dictionary<int, List<string>>();

                var teams = entities.Projects.Find(id).Teams;

                foreach (var team in teams)
                {
                    var userList = team.Users.Select(user => user.UserName).ToList();

                    teamMembers.Add(team.ID, userList);
                }
                ViewBag.TeamMembers = teamMembers;

                // USER ROLES
                var teamUsers = new Dictionary<string, List<string>>();
                var users = entities.Projects.Find(id).Users;

                foreach (var user in users)
                {
                    var roleList = user.AspNetRoles.Select(role => role.Name).ToList();
                    teamUsers.Add(user.Id,roleList);
                }
                ViewBag.TeamMemberRoles = teamUsers;

                return View(proj);
            }
            return View();
        }

        // GET: Project/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Project/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                using (var entities = new ScrumDB())
                {
                    entities.Projects.Add(new Project()
                    {
                        Name = collection["Name"]
                    });
                    entities.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        // GET: Project/Edit/5
        public ActionResult Edit(int id)
        {
            //TODO: add error handling here
            using (var entities = new ScrumDB())
            {
                var proj = entities.Projects.Find(id);
                if (proj == null)
                {
                    ViewBag.ErrorMessage = string.Format("Project id {0} was not found.", id);
                    return RedirectToAction("Index");
                }
                return View(proj);
            }
        }

        // POST: Project/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                using (var entities = new ScrumDB())
                {
                    var proj = entities.Projects.Find(id);
                    // update the information
                    proj.Name = collection["Name"];
                    entities.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        // GET: Project/Delete/5
        public ActionResult Delete(int id)
        {
            using (var entities = new ScrumDB())
            {
                var proj = entities.Projects.Find(id);
                if (proj == null)
                {
                    ViewBag.ErrorMessage = string.Format("Project id {0} was not found.", id);
                    return RedirectToAction("Index");
                }
                return View(proj);
            }
        }

        // POST: Project/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                using (var entities = new ScrumDB())
                {
                    var proj = entities.Projects.Find(id);
                    if (proj == null)
                    {
                        ViewBag.ErrorMessage = string.Format("Project id {0} was not found.", id);
                        return RedirectToAction("Index");
                    }
                    entities.Projects.Remove(proj);
                    entities.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        [HttpGet]
        public ActionResult ProjectBacklog(int id)
        {
            using (var entities = new ScrumDB())
            {
                var proj = entities.Projects.Find(id);
                if (proj == null) return View("Index");
                ViewBag.ProjectID = proj.ID;
                ViewBag.ProjectTitle = proj.Name;
                var projBacklogList = ProjectBacklogItems(proj);
                return View(projBacklogList);
            }
            
        }


        public ActionResult ProjectBoard(int id)
        {
            using (var entities = new ScrumDB())
            {

                var proj = entities.Projects.Find(id);
                if (proj == null) return View("Index");
                ViewBag.ProjectID = proj.ID;
                ViewBag.ProjectTitle = proj.Name;
                var projBacklogList = ProjectBacklogItems(proj);
                return View(projBacklogList);
            }
        }

        /// <summary>
        /// Gets the full list of project backlog items
        /// </summary>
        /// <param name="proj"></param>
        /// <returns></returns>
        private List<ProjectBacklogItem> ProjectBacklogItems(Project proj)
        {
            var projBacklogList = proj.BacklogItems.Select(backlogItem => new ProjectBacklogItem()
            {
                Name = backlogItem.Name,
                Comments = backlogItem.Comments,
                State = backlogItem.State,
                TaskCount = backlogItem.Tasks.Count,
                Priority = backlogItem.Priority,
                Id = backlogItem.ID
            })
            .Where(o => o.State != ProjectBacklogItem.BacklogItemState.Removed)
            .OrderBy(o => o.Priority)
            .ToList();
            return projBacklogList;
        }

        [HttpGet]
        public ActionResult TeamUserManage(int projectId)
        {
            Project project = null;
            using (var db = new ScrumDB())
            {
                project = db.Projects
                    .Include("Users")
                    .Include("Teams").ToList()
                    .FirstOrDefault(p => p.ID == projectId);

                var projectUsers = db.AspNetUsers.Where(u => u.Projects.Any(p => p.ID == projectId));


                if (project.Teams.Count > 0)
                {
                    var projectTeams = db.Teams.ToList().Except(project.Teams);
                    if (projectTeams.Any()) ViewBag.AllOtherTeams = projectTeams.ToList();
                }
                else
                {
                    ViewBag.AllOtherTeams = db.Teams.ToList();
                }

                if (projectUsers.Any())
                {
                    var projectUserCollection = db.AspNetUsers.ToList().Except(projectUsers);

                    if (projectUserCollection.Any()) ViewBag.AllOtherUsers = projectUserCollection.ToList();
                }
                else
                {
                    ViewBag.AllOtherUsers = db.AspNetUsers.ToList();
                }
            }
            return PartialView("TeamUserManage", project);
        }

        [HttpPost]
        public ActionResult SubmitProjectTeamsUsers(int projectId, int[] teamsArray, string[] usersArray)
        {
            try
            {
                using (var db = new ScrumDB())
                {

                    // get the project
                    var project = db.Projects.Find(projectId);

                    // get all the users
                    var allUsers = db.AspNetUsers.Select(u => u.UserName);
                    var allTeams = db.Teams.Select(t => t.ID);

                    // get the projects's current users
                    var currentProjectUsers = project.Users.Select(u => u.UserName).ToList();
                    var currentProjectTeamIDs = project.Teams.Select(t => t.ID).ToList();

                    // check for no teams
                    if (teamsArray == null || teamsArray.Count() == 0)
                    {
                        foreach (var team in currentProjectTeamIDs)
                        {
                            project.Teams.Remove(db.Teams.FirstOrDefault(t => t.ID == team));
                        }

ScrumTool/Controllers/ScrumTaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Microsoft.Ajax.Utilities;
using ScrumTool.Database;

namespace ScrumTool.Controllers
{
    public class ScrumTaskController : BaseController
    {
        //// GET: ScrumTask
        //public ActionResult Index()
        //{
        //    return View();
        //}

        // GET: ScrumTask/Details/5
        public ActionResult Details(int id)
        {
            using (var entities = new ScrumDB())
            {
                var backlogItem = entities.Tasks.Find(id);
                return View(backlogItem);
            }
        }

        // GET: ScrumTask/Create
        public ActionResult Create(int? id)
        {
            if (id == null) return View();
            ViewBag.BacklogItemID = id;
            return View();
        }

        // POST: ScrumTask/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                int backlogItemId = -1;
                using (var entities = new ScrumDB())
                {
                    backlogItemId = int.Parse(collection["BacklogItemID"]);
                    entities.Tasks.Add(new ScrumTask
                    {
                        Name = collection["Name"],
                        BacklogItemID = backlogItemId,
                        Weight = int.Parse(collection["Weight"]),
                        Comments = collection["Comments"]
                    });
                    entities.SaveChanges();
                }
                if (backlogItemId > -1)
                    return RedirectToAction("Details", "BacklogItem", new {id = backlogItemId});
                else
                    throw new Exception("Backlog item ID is invalid.");
            }
            catch (Exception e)
            {
                return View(); // TODO: change this
            }
        }

        // GET: ScrumTask/Edit/5
        public ActionResult Edit(int id)
        {
            using (var entities = new ScrumDB())
            {
                return View(entities.Tasks.Find(id));
            }
        }

        // POST: ScrumTask/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                using (var entities = new ScrumDB())
                {
                    var item = entities.Tasks.Find(id);
                    if (item == null) return RedirectToAction("Details", new { id = id });

                    item.Name = collection["Name"];
                    item.Weight = int.Parse(collection["Weight"]);
                    item.Comments = collection["Comments"];
                    entities.SaveChanges();

                    return View("Details",item);
                }          
            }
            catch (Exception e)
            {
                return RedirectToAction("Details", new { id = id });
            }
        }

        // POST: ScrumTask/Remove/5
        [HttpPost]
        public ActionResult Remove(int id)
        {
            try
            {
                using (var entities = new ScrumDB())
                {
                    var item = entities.Tasks.Find(id);
                    if(item == null) return new HttpNotFoundResult();
                    entities.Tasks.Remove(item);
                    entities.SaveChanges();
                    return new HttpStatusCodeResult(HttpStatusCode.OK);
                }
            }
            catch (Exception)
            {
                // TODO: something here
                throw;
            }
        }

        //// GET: ScrumTask/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: ScrumTask/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

ScrumTool/Views/BacklogItem/Create.cshtml
@model ScrumTool.Database.BacklogItem

@{
    ViewBag.Title = "Create Backlog Item";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>New Backlog Item</h4>
        <hr />
        @Html.HiddenFor(m => m.ProjectID, new { id = "ProjectID" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Back to Project Backlog" class="btn btn-default" onclick='window.location="/Project/ProjectBacklog/@Html.Raw(Model.ProjectID)"' />
                <input type="submit" value="Create" class="btn btn-default btn-success"/>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ScrumTool/Views/BacklogItem/Details.cshtml
@using System.Net.Configuration
@using ScrumTool.Database
@model ScrumTool.Database.BacklogItem

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <h4>Backlog Item Details - @Html.Raw(Model.Name)</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProjectID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

    </dl>
</div>
<div class="btn-group btn-group-sm">
    @Html.ActionLink("Project Backlog", "ProjectBacklog", "Project", new { id = Model.ProjectID }, new { @class = "btn btn-default" })
    @Html.ActionLink("Project Board", "ProjectBoard", "Project", new { id = Model.ProjectID }, new { @class = "btn btn-default" })
</div>
<br/><br/>

<div class="btn-group btn-group-sm">
    @Html.ActionLink("Edit Item", "Edit", new {id = Model.ID}, new {@class = "btn btn-default"})
    @*@Html.ActionLink("Delete Item", "Remove", new { id = Model.ID }, new { @class = "btn btn-default" })*@
    @Html.ActionLink("Add Task", "Create", "ScrumTask", new { id = Model.ID }, new { @class = "btn btn-default" })
</div>
<hr/>

<h4>ScrumTask List</h4>
@Html.Partial("_TaskListPartial", (List<ScrumTask>)ViewBag.BacklogItemTaskList)
@Html.Partial("_MobileTaskListPartial", (List<ScrumTask>)ViewBag.BacklogItemTaskList)

ScrumTool/Views/BacklogItem/Edit.cshtml
@using ScrumTool.Objects
@model ScrumTool.Database.BacklogItem

@{
    ViewBag.Title = "Edit Backlog Item";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BacklogItem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProjectID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjectID, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.State, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.State, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="button" onclick="window.location = '/BacklogItem/Details/@Html.Raw(Model.ID)'" class="btn btn-default">Back to Backlog Item</button>
                <input type="submit" value="Save" class="btn btn-default btn-success"/>

            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ScrumTool/Views/BacklogItem/TaskList.cshtml
@model IEnumerable<ScrumTool.Database.ScrumTask>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Weight)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comments)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BacklogItem.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Weight)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comments)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BacklogItem.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

ScrumTool/Views/BacklogItem/_MobileTaskListPartial.cshtml
@model ICollection<ScrumTool.Database.ScrumTask>
<div id="mobile-task-list">
    @if (Model.Count == 0)
    {
        <h3>No tasks</h3>
    }
    else
    {
        foreach (var item in Model)
        {
            <div class="task-box" id="@item.ID">
                <h4 class="task-name">@item.Name</h4>
                <p class="task-count">@item.Weight</p>
                <br/>
                <p class="comment-para">@item.Comments</p>
            </div>
        }
    }
</div>