ScrumTool/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using ScrumTool.Database;
using ScrumTool.Models;
using ScrumTool.Objects;

namespace ScrumTool.Controllers
{
    public class SettingsController : Controller
    {
        // GET: Settings
        public ActionResult Index()
        {
            using (var entities = new ScrumDB())
            {
                var user = entities.AspNetUsers.FirstOrDefault(u => u.Email == HttpContext.User.Identity.Name);
                if (user != null) ViewBag.UserRoles = user.AspNetRoles.ToList();
                return View();
            }
        }

        // GET: Settings/Admin
        public ActionResult Admin()
        {
            List<AspNetUser> aspNetUserList;
            using (var entities = new ScrumDB())
            {
                aspNetUserList = entities.AspNetUsers.Include("AspNetRoles").ToList();
            }
            return View(aspNetUserList);
        }

        [HttpPost]
        public ActionResult ResetPassword(string username)
        {
            using (var entities = new ScrumDB())
            {
                var user = Membership.GetUser(username);
                if (user != null)
                {
                    var newPassword = user.ResetPassword();
                    return new HttpStatusCodeResult(HttpStatusCode.OK, newPassword);
                }
                else
                {
                    return new HttpNotFoundResult();
                }
            }
        }

        [HttpGet]
        public ActionResult UserGroups(string username)
        {
            UserManage manageModel = new UserManage(username);
            return PartialView(manageModel);
        }

        [HttpPost]
        public ActionResult ChangeUserRoles(string[] roles, string username)
        {
            try
            {
                using (var db = new ScrumDB())
                {
                    // get all the user roles
                    var allUserRoles = db.AspNetRoles.Select(r => r.Name).ToList();

                    // get the user
                    var user = db.AspNetUsers.FirstOrDefault(u => u.UserName == username);

                    // get the user's current roles
                    var currentUserRolesCollection = user.AspNetRoles;
                    var currentUserRoles = currentUserRolesCollection.Select(r => r.Name).ToList();


                    if (roles == null || !roles.Any())
                    {
                        foreach (var role in currentUserRoles)
                        {
                            user.AspNetRoles.Remove(db.AspNetRoles.FirstOrDefault(r => r.Name == role));
                        }
                    }
                    else
                    {
                        // get the roles to add and remove
                        var rolesToAdd = roles.Except(currentUserRoles).ToArray();
                        var rolesToRemove = allUserRoles.Except(roles).ToArray();

                        // perform database operations
                        foreach (var item in rolesToRemove)
                        {
                            user.AspNetRoles.Remove(db.AspNetRoles.FirstOrDefault(r => r.Name == item));
                        }
                        foreach (var item in rolesToAdd)
                        {
                            user.AspNetRoles.Add(db.AspNetRoles.FirstOrDefault(r => r.Name == item));
                        }
                    }

                    // save changes
                    db.SaveChanges();
                }
                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            catch (Exception e)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, e.Message);
            }
        }

    }
}

ScrumTool/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Management.Instrumentation;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ScrumTool.Database;
using WebGrease.Css.Extensions;

namespace ScrumTool.Controllers
{
    [Authorize]
    public class TeamController : BaseController
    {
        // GET: Team
        public ActionResult Index()
        {
            using (var entities = new ScrumDB())
            {
                return View(entities.Teams.ToList());
            }
        }

        // GET: Team/Details/5
        public ActionResult Details(int id)
        {
            using (var entities = new ScrumDB())
            {
                try
                {
                    var team = entities.Teams.Find(id);
                    var teamUsers = entities.AspNetUsers.Where(u => u.Teams.Any(t => t.ID == id))
                        .Include("AspNetRoles").ToList();
                    ViewBag.teamUsers = teamUsers;
                    return View(team);
                }
                catch (Exception e)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, e.Message);
                }
            }
        }

        // GET: Team/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Team/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                using (var entities = new ScrumDB())
                {
                    entities.Teams.Add(new Team()
                    {
                        Name = collection["Name"]
                    });
                    entities.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, e.Message);
            }
        }

        // GET: Team/Edit/5
        public ActionResult Edit(int id)
        {
            using (var entities = new ScrumDB())
            {
                var team = entities.Teams.Find(id);
                return View(team);
            }
        }

        // POST: Team/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                using (var entities = new ScrumDB())
                {
                    var team = entities.Teams.Find(id);
                    if (team == null) throw new InstanceNotFoundException();
                    team.Name = collection["Name"];
                    entities.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (InstanceNotFoundException exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            catch (Exception e)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, e.Message);
            }
        }

        // GET: Team/Delete/5
        public ActionResult Delete(int id)
        {
            using (var entities = new ScrumDB())
            {
                var team = entities.Teams.Find(id);
                if (team == null)
                {
                    ViewBag.ErrorMessage = string.Format("Team with ID {0} not found.", id);
                    return RedirectToAction("Index");
                }
                return View(team);
            }
        }

        // POST: Team/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                using (var entities = new ScrumDB())
                {
                    var team = entities.Teams.Find(id);
                    if (team == null)
                    {
                        ViewBag.ErrorMessage = string.Format("Team with ID {0} not found.", id);
                        return RedirectToAction("Index");
                    }
                    entities.Teams.Remove(team);
                    entities.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, e.Message);
            }
        }

        [HttpPost]
        public ActionResult AddUserToTeam(int teamId, string username)
        {
            try
            {
                using (var entities = new ScrumDB())
                {
                    var team = entities.Teams.Find(teamId);
                    team.Users.Add(entities.AspNetUsers.FirstOrDefault(u => u.UserName == username));
                    entities.SaveChanges();
                    return new HttpStatusCodeResult(HttpStatusCode.OK);
                }
            }
            catch (Exception e)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, e.Message);
            }
        }

        public ActionResult Manage(int team)
        {
            try
            {
                using (var db = new ScrumDB())
                {
                    var allUsersInTeam = db.AspNetUsers.Where(u => u.Teams.Any(t => t.ID == team));

                    ViewBag.AllOtherUsers = db.AspNetUsers.Except(allUsersInTeam).ToList();

                    return PartialView("Manage", 
                        db.Teams.Where(t => t.ID == team)
                            .Include("Users")
                            .Include("Users.AspNetRoles")
                            .ToList()
                            .FirstOrDefault());
                }
            }
            catch (Exception e)
            {         
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, e.Message);
            }
        }

        [HttpPost]
        public ActionResult TeamUsers(string[] users, int teamId )
        {
            try
            {
                using (var db = new ScrumDB())
                {
                    // get all the users
                    var allUsers = db.AspNetUsers.Select(u => u.UserName);

                    // get the team
                    var team = db.Teams.Find(teamId);

                    // get the team's current users
                    var currentTeamUsers = team.Users;
                    var currentTeamUsersList = currentTeamUsers.Select(u => u.UserName).ToList();

                    
                    // if there are no users in the list we just need to remove them all
                    if (users == null || users.Length == 0)
                    {
                        foreach (var user in currentTeamUsersList)
                        {
                            team.Users.Remove(db.AspNetUsers.FirstOrDefault(u => u.UserName == user));
                        }
                        db.SaveChanges();
                        return new HttpStatusCodeResult(HttpStatusCode.OK);
                    }

                    // get the users to add and remove
                    var usersToAdd = users.Except(currentTeamUsersList).ToArray();
                    var usersToRemove = allUsers.Except(users).ToArray();

                    // perform database operations
                    foreach (var item in usersToRemove)
                    {
                        team.Users.Remove(db.AspNetUsers.FirstOrDefault(r => r.UserName == item));
                    }
                    foreach (var item in usersToAdd)
                    {
                        team.Users.Add(db.AspNetUsers.FirstOrDefault(r => r.UserName == item));
                    }

                    // save changes
                    db.SaveChanges();
                }
                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            catch (Exception e)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, e.Message);
            }
        }

    }
}

ScrumTool/Views/Shared/_BacklogItemBox.cshtml
@model ScrumTool.Objects.ProjectBacklogItem


<div class="backlog-item" id="@Model.Id">
    <div class="flipper">
        <div class="front">
            <h4 class="task-name">@Model.Name - @Html.Raw(Model.TaskCount) tasks</h4>
            <br />
            <p class="comment-para">@Model.Comments</p>
        </div>
        <div class="back">
            <h4 class="task-name">@Model.Name - @Html.Raw(Model.TaskCount) tasks</h4>
            <br/>
            <div class="btn-group rear-btn-group">
                <a class="rear-button rear-button-details btn btn-default" data-backlog-id="@Model.Id">Details</a>
                <a class="rear-button rear-button-edit btn btn-default" data-backlog-id="@Model.Id">Edit</a>
                <a class="rear-button rear-button-remove btn btn-danger" data-backlog-id="@Model.Id">Remove</a>
            </div>
        </div>
    </div>
</div>

ScrumTool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link rel="icon" href="~/favicon.png">
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>@ViewBag.Title - SCRUM Tool</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/signalr")


    <script src="~/Scripts/Config.js"></script>
    <script src="~/signalr/hubs"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/Home/Index">
                    <img src="~/Content/Images/AirScrum_Logo_1_White.png" id="scrum-logo-header" alt="Scrum Tool Logo" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Teams", "Index", "Team")</li>
                        <li>@Html.ActionLink("Projects", "Index", "Project")</li>
                        if (User.IsInRole("Admin"))
                        {
                            <li>@Html.ActionLink("Admin", "Admin", "Settings")</li>
                        }
                    }
                    <li>@Html.ActionLink("Changelog", "Changelog", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year Jamie Roos - Open Source SCRUM Tool</p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

ScrumTool/Views/Shared/_TaskListPartial.cshtml
@model ICollection<ScrumTool.Database.ScrumTask>
<div id="task-list-large">
    @if (Model.Count == 0)
    {
        <h3>No tasks</h3>
    }
    else
    {
        <table data-toggle="table" data-classes="table table-condensed" data-striped="true" data-sort-name="item-id" data-sort-order="asc"
               class="task-list">
            <tr>
                <td>Name</td>
                <td>Comments</td>
                <td>Weight</td>
                <td>&nbsp;</td>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td data-field="item-name">@item.Name</td>
                    <td data-field="item-comments">@item.Comments</td>
                    <td data-field="item-weight">@item.Weight</td>
                    <td data-field="details-link"> <button type="button" onclick="window.location = '/ScrumTask/Details/@Html.Raw(item.ID)'" class="btn btn-default btn-sm">Details</button> </td>
                </tr>
            }
        </table>
    }
    
</div>