ScrumTool/Controllers/BacklogItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ScrumTool.Database;
using ScrumTool.Objects;

namespace ScrumTool.Controllers
{
    public class BacklogItemController : BaseController
    {
        // GET: BacklogItem
        //public ActionResult Index()
        //{
        //    return View();
        //}

        // GET: BacklogItem/Details/5
        public ActionResult Details(int id)
        {
            using (var entities = new ScrumDB())
            {

                var item = entities.BacklogItems.Find(id);
                ViewBag.BacklogItemTaskList = item.Tasks.ToList();
                return View(item);
            }
        }

        // GET: BacklogItem/Create
        public ActionResult Create(int? id)
        {
            if (id == null) return View();
            var item = new BacklogItem
            {
                ProjectID = (int) id
            };
            return View(item);
        }

        // POST: BacklogItem/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                using (var entities = new ScrumDB())
                {
                    entities.BacklogItems.Add(new BacklogItem()
                    {
                        Name = collection["Name"],
                        ProjectID = int.Parse(collection["ProjectID"]),
                        Comments = collection["Comments"],
                        State = 0
                    });
                    entities.SaveChanges();
                }
                return RedirectToAction("ProjectBacklog","Project",new{id = collection["ProjectID"]});
            }
            catch
            {
                return View();
            }
        }

        // GET: BacklogItem/Edit/5
        public ActionResult Edit(int id)
        {
            using (var entities = new ScrumDB())
            {
                return View(entities.BacklogItems.Find(id));
            }
        }

        // POST: BacklogItem/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                try
                {
                    using (var entities = new ScrumDB())
                    {
                        var bli = entities.BacklogItems.Find(id);
                        bli.Name = collection["Name"];
                        bli.ProjectID = int.Parse(collection["ProjectID"]);
                        bli.Comments = collection["Comments"];
                        bli.State = (ProjectBacklogItem.BacklogItemState)int.Parse(collection["State"]);

                        entities.SaveChanges();
                    }
                    return RedirectToAction("ProjectBacklog", "Project", new { id = collection["ProjectID"] });
                }
                catch
                {
                    return View();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: BacklogItem/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: BacklogItem/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult StateChange(int backlogItemId, int newState)
        {
            using (var entities = new ScrumDB())
            {
                try
                {
                    var item = entities.BacklogItems.Find(backlogItemId);
                    item.State = (ProjectBacklogItem.BacklogItemState)newState;
                    item.Priority = null;
                    entities.SaveChanges();
                }
                catch (Exception ex)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, ex.Message);
                }
            }
            return new HttpStatusCodeResult(200);
        }

        [HttpPost]
        public ActionResult PriorityChange(int projId, int[] idArray)
        {
            using (var entities = new ScrumDB())
            {
                try
                {
                    var itemList = entities.BacklogItems.Where(i => i.ProjectID == projId && i.State != ProjectBacklogItem.BacklogItemState.Removed);

                    foreach (var item in itemList)
                    {
                        item.Priority = Array.IndexOf(idArray, item.ID); // assign the priority of the item according to it's position in the array
                    }

                    entities.SaveChanges();
                }
                catch (Exception ex)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, ex.Message);
                }
            }
            return new HttpStatusCodeResult(200);
        }

        [HttpPost]
        public ActionResult BacklogItemTasks(int id)
        {
            using (var entities = new ScrumDB())
            {
                var backlogItem = entities.BacklogItems.Find(id);
                if (backlogItem == null) return HttpNotFound();
                var tasks = backlogItem.Tasks.ToList();
                return PartialView("_TaskListPartial", tasks);
            }
        }

    }
}

ScrumTool/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Common.CommandTrees;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using ScrumTool.Database;
using ScrumTool.Objects;

namespace ScrumTool.Controllers
{
    [Authorize]
    public class ProjectController : BaseController
    {
        // GET: Project
        public ActionResult Index()
        {
            using (var entities = new ScrumDB())
            {
                try
                {
                    return View(entities.Projects.ToList());
                }
                catch (Exception e)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, e.Message);
                }
                
            }
        }

        // GET: Project/Details/5
        public ActionResult Details(int id)
        {
            //TODO: add error handling here
            using (var entities = new ScrumDB())
            {
                var proj = entities.Projects.Include("Teams").Include("Users").FirstOrDefault(p => p.ID == id);
                if (proj == null)
                {
                    ViewBag.ErrorMessage = string.Format("Project id {0} was not found.", id);
                    return RedirectToAction("Index");
                }
                var allBacklogItems = entities.BacklogItems.Where(b => b.ProjectID == id);
                ViewBag.BacklogItems = allBacklogItems;

                // TEAM MEMBERS
                var teamMembers = new Dictionary<int, List<string>>();

                var teams = entities.Projects.Find(id).Teams;

                foreach (var team in teams)
                {
                    var userList = team.Users.Select(user => user.UserName).ToList();

                    teamMembers.Add(team.ID, userList);
                }
                ViewBag.TeamMembers = teamMembers;

                // USER ROLES
                var teamUsers = new Dictionary<string, List<string>>();
                var users = entities.Projects.Find(id).Users;

                foreach (var user in users)
                {
                    var roleList = user.AspNetRoles.Select(role => role.Name).ToList();
                    teamUsers.Add(user.Id,roleList);
                }
                ViewBag.TeamMemberRoles = teamUsers;

                return View(proj);
            }
            return View();
        }

        // GET: Project/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Project/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                using (var entities = new ScrumDB())
                {
                    entities.Projects.Add(new Project()
                    {
                        Name = collection["Name"]
                    });
                    entities.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        // GET: Project/Edit/5
        public ActionResult Edit(int id)
        {
            //TODO: add error handling here
            using (var entities = new ScrumDB())
            {
                var proj = entities.Projects.Find(id);
                if (proj == null)
                {
                    ViewBag.ErrorMessage = string.Format("Project id {0} was not found.", id);
                    return RedirectToAction("Index");
                }
                return View(proj);
            }
        }

        // POST: Project/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                using (var entities = new ScrumDB())
                {
                    var proj = entities.Projects.Find(id);
                    // update the information
                    proj.Name = collection["Name"];
                    entities.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        // GET: Project/Delete/5
        public ActionResult Delete(int id)
        {
            using (var entities = new ScrumDB())
            {
                var proj = entities.Projects.Find(id);
                if (proj == null)
                {
                    ViewBag.ErrorMessage = string.Format("Project id {0} was not found.", id);
                    return RedirectToAction("Index");
                }
                return View(proj);
            }
        }

        // POST: Project/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                using (var entities = new ScrumDB())
                {
                    var proj = entities.Projects.Find(id);
                    if (proj == null)
                    {
                        ViewBag.ErrorMessage = string.Format("Project id {0} was not found.", id);
                        return RedirectToAction("Index");
                    }
                    entities.Projects.Remove(proj);
                    entities.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        [HttpGet]
        public ActionResult ProjectBacklog(int id)
        {
            using (var entities = new ScrumDB())
            {
                var proj = entities.Projects.Find(id);
                if (proj == null) return View("Index");
                ViewBag.ProjectID = proj.ID;
                ViewBag.ProjectTitle = proj.Name;
                var projBacklogList = ProjectBacklogItems(proj);
                return View(projBacklogList);
            }
            
        }


        public ActionResult ProjectBoard(int id)
        {
            using (var entities = new ScrumDB())
            {

                var proj = entities.Projects.Find(id);
                if (proj == null) return View("Index");
                ViewBag.ProjectID = proj.ID;
                ViewBag.ProjectTitle = proj.Name;
                var projBacklogList = ProjectBacklogItems(proj);
                return View(projBacklogList);
            }
        }

        /// <summary>
        /// Gets the full list of project backlog items
        /// </summary>
        /// <param name="proj"></param>
        /// <returns></returns>
        private List<ProjectBacklogItem> ProjectBacklogItems(Project proj)
        {
            var projBacklogList = proj.BacklogItems.Select(backlogItem => new ProjectBacklogItem()
            {
                Name = backlogItem.Name,
                Comments = backlogItem.Comments,
                State = backlogItem.State,
                TaskCount = backlogItem.Tasks.Count,
                Priority = backlogItem.Priority,
                Id = backlogItem.ID
            })
            .Where(o => o.State != ProjectBacklogItem.BacklogItemState.Removed)
            .OrderBy(o => o.Priority)
            .ToList();
            return projBacklogList;
        }

        [HttpGet]
        public ActionResult TeamUserManage(int projectId)
        {
            Project project = null;
            using (var db = new ScrumDB())
            {
                project = db.Projects
                    .Include("Users")
                    .Include("Teams").ToList()
                    .FirstOrDefault(p => p.ID == projectId);

                var projectUsers = db.AspNetUsers.Where(u => u.Projects.Any(p => p.ID == projectId));


                if (project.Teams.Count > 0)
                {
                    var projectTeams = db.Teams.ToList().Except(project.Teams);
                    if (projectTeams.Any()) ViewBag.AllOtherTeams = projectTeams.ToList();
                }
                else
                {
                    ViewBag.AllOtherTeams = db.Teams.ToList();
                }

                if (projectUsers.Any())
                {
                    var projectUserCollection = db.AspNetUsers.ToList().Except(projectUsers);

                    if (projectUserCollection.Any()) ViewBag.AllOtherUsers = projectUserCollection.ToList();
                }
                else
                {
                    ViewBag.AllOtherUsers = db.AspNetUsers.ToList();
                }
            }
            return PartialView("TeamUserManage", project);
        }

        [HttpPost]
        public ActionResult SubmitProjectTeamsUsers(int projectId, int[] teamsArray, string[] usersArray)
        {
            try
            {
                using (var db = new ScrumDB())
                {

                    // get the project
                    var project = db.Projects.Find(projectId);

                    // get all the users
                    var allUsers = db.AspNetUsers.Select(u => u.UserName);
                    var allTeams = db.Teams.Select(t => t.ID);

                    // get the projects's current users
                    var currentProjectUsers = project.Users.Select(u => u.UserName).ToList();
                    var currentProjectTeamIDs = project.Teams.Select(t => t.ID).ToList();

                    // check for no teams
                    if (teamsArray == null || teamsArray.Count() == 0)
                    {
                        foreach (var team in currentProjectTeamIDs)
                        {
                            project.Teams.Remove(db.Teams.FirstOrDefault(t => t.ID == team));
                        }

ScrumTool/Views/Project/Create.cshtml
@model ScrumTool.Database.Project

@{
    ViewBag.Title = "Create Project";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add New Project</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Back to Project List", "Index", "Project", new { @class = "btn btn-default" })
                <input type="submit" value="Create" class="btn btn-default btn-success"/>
            </div>
        </div>
    </div>
}

<div>
    
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ScrumTool/Views/Project/Delete.cshtml
@model ScrumTool.Database.Project

@{
    ViewBag.Title = "Delete Project";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-default" })
            <input type="submit" value="Delete" class="btn btn-default btn-danger"/>
        </div>
    }
</div>

ScrumTool/Views/Project/Details.cshtml
@model ScrumTool.Database.Project

@{
    ViewBag.Title = "Project Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Project Details</h2>

<div>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<button class="btn btn-default" id="manage-assigned-project-teams" data-url="@Url.Action("TeamUserManage", new {projectId = Model.ID})" data-project-id="@Model.ID">
    Manage Assigned Teams
</button>
<div>
    <table data-toggle="table" data-classes="table table-condensed" data-striped="true">
        <tr>
            <td colspan="2">
                <h3>Assigned Teams</h3>
            </td>
        </tr>
        @if (Model.Teams.Count > 0)
        {
            <tr>
                <td>
                    Team Name
                </td>
                <td>
                    Users
                </td>
            </tr>
            foreach (var team in Model.Teams)
             {
                 <tr>
                     <td>
                         @team.Name
                     </td>
                     <td>
                         <ul>
                             @foreach (var user in ViewBag.TeamMembers[team.ID])
                             {
                                 <li>
                                     @user
                                 </li>
                             }
                         </ul>
                     </td>
                 </tr>
             }
        }
        else
        {
            <tr>
                <td colspan="2">
                    <h4>No assigned teams</h4>
                </td>
            </tr>
        }
        <tr>
            <td colspan="2">
                <h3>Assigned Users</h3>
            </td>
        </tr>
        @if (Model.Users.Count > 0)
        {
            
            <tr>
                <td>
                    User Name
                </td>
                <td>
                    Roles
                </td>
            </tr>
            foreach (var user in Model.Users)
             {
                 <tr>
                     <td>
                         @user.UserName
                     </td>
                     <td>
                         <ul>
                             @foreach (var role in ViewBag.TeamMemberRoles[user.Id])
                             {
                                 <li>
                                     @role
                                 </li>
                             }
                         </ul>
                     </td>
                 </tr>
             }
        }
        else
        {
            <tr>
                <td colspan="2">
                    <h4>No assigned users</h4>
                </td>
            </tr>
        }
    </table>
</div>
<div>
    
    <table data-toggle="table" data-classes="table table-condensed" data-striped="true">
        
        
    </table>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new {id = Model.ID}, new {@class = "btn btn-default"})
    @Html.ActionLink("Back", "Index", new {}, new {@class = "btn btn-default"})
</p>

<script src="~/Scripts/ProjectDetails.js" type="text/javascript"></script>

ScrumTool/Views/Project/Edit.cshtml
@model ScrumTool.Database.Project

@{
    ViewBag.Title = "Edit Project";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Project - @Model.Name</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Project Backlog","ProjectBacklog", "Project", new { id = Model.ID}, new { @class = "btn btn-default"})
                @Html.ActionLink("Project Board", "ProjectBoard", "Project", new { id = Model.ID }, new { @class = "btn btn-default" })
                <input type="submit" value="Save Changes" class="btn btn-default btn-success"/>

            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ScrumTool/Views/Project/Index.cshtml
@model IEnumerable<ScrumTool.Database.Project>

@{
    ViewBag.Title = "Projects";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Projects</h2>

<p>
    @Html.ActionLink("Add New", "Create",new{},new {@class = "btn btn-default btn-sm"})
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>Actions</th>
    </tr>

    @foreach (var item in Model) {
        <tr class="project-row">
            <td class="project-name">
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @*<div class="btn-group btn-group-sm">
                    <button id="proj-drop-@Html.Raw(item.ID)" class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                        Actions
                        <span class="carat"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="proj-drop-@Html.Raw(item.ID)">
                        <li role="presentation">
                            @Html.ActionLink("Edit", "Edit", new { id = item.ID, role = "menuitem", tabindex = "-1" })
                        </li>
                        <li role="presentation">
                            @Html.ActionLink("Details", "Details", new { id = item.ID })
                        </li>
                        <li role="presentation">
                            @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                        </li>
                    </ul>
                </div>*@
            
                <div class="btn-group btn-group-sm">
                    @Html.ActionLink("Backlog","ProjectBacklog","Project", new { id = @item.ID }, new { @class = "btn btn-default"})
                    @Html.ActionLink("Board", "ProjectBoard", "Project", new { id = @item.ID }, new { @class = "btn btn-default" })
                    @Html.ActionLink("Edit", "Edit", "Project", new { id = @item.ID }, new { @class = "btn btn-default" })
                    @Html.ActionLink("Details", "Details", "Project", new { id = @item.ID }, new { @class = "btn btn-default" })
                    @Html.ActionLink("Delete", "Delete", "Project", new { id = @item.ID }, new { @class = "btn btn-default" })
                </div>
            
            </td>
        </tr>
    }
</table>

ScrumTool/Views/Project/ProjectBacklog.cshtml
@model List<ScrumTool.Objects.ProjectBacklogItem>
@using ScrumTool.Logic
@using ScrumTool.Objects
@{
    ViewBag.Title = "Backlog";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="../../Scripts/ProjectBacklog.js" type="text/javascript"></script>

<div id="top-area">
    <h2>
        Project Backlog - @ViewBag.ProjectTitle (Project ID <span id="proj-id">@ViewBag.ProjectID</span>)
    </h2>
    <div class="btn-group btn-group-sm">
        @Html.ActionLink("Board", "ProjectBoard", "Project", new {id = ViewBag.ProjectID}, new {@class = "btn btn-default"})
        @Html.ActionLink("Add Item", "Create", "BacklogItem", new {id = ViewBag.ProjectID}, new {@class = "btn btn-default"})
        @Html.ActionLink("Modify Project", "Edit", "Project", new {id = ViewBag.ProjectID}, new {@class = "btn btn-default"})
    </div>
</div>
<div id="help-area">
    <h4><span class="fa fa-question-circle"></span>Reorder the priority of the tasks by dragging and dropping the tasks into order</h4>
</div>
<div id="bottom-area">
    <ul id="sortable-project-backlog">
        @foreach (var item in Model)
        {
            <li class="ui-state-default" id="@item.Id" data-sort-id="id_@Html.Raw(item.Id)">
                <span class="fa fa-bars"></span>
                @Html.Raw(item.Name) - @Html.Raw(item.State.GetDisplayAttributeFrom(typeof(ProjectBacklogItem.BacklogItemState)))
                <br/>
                <span class="backlog-item-comments">@Html.Raw(item.Comments)</span>
                <br/>
                <div class="backlog-item-accordion" data-id="@item.Id">
                    <h3><span class="fa fa-plus"></span>Item Tasks</h3>
                    <div class="backlog-item-accordion-inner">
                        <span class="fa fa-spinner fa-pulse"></span>
                    </div>
                </div>
            </li>
        }
    </ul>
</div>

@Html.Partial("_Context_Backlog")

ScrumTool/Views/Project/ProjectBoard.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@model List<ScrumTool.Objects.ProjectBacklogItem>
@using ScrumTool.Logic
@using ScrumTool.Objects
@{
    ViewBag.Title = "Backlog";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="../../Scripts/ProjectBoard.js" type="text/javascript"></script>

<div id="top-area">
    <h2>Project Backlog - @ViewBag.ProjectTitle</h2>
    <div class="btn-group btn-group-sm">
        @Html.ActionLink("Backlog", "ProjectBacklog", "Project", new {id = ViewBag.ProjectID}, new {@class = "btn btn-default"})
        @Html.ActionLink("Add Item", "Create", "BacklogItem", new {id = ViewBag.ProjectID}, new {@class = "btn btn-default"})
        @Html.ActionLink("Modify Project", "Edit", "Project", new {id = ViewBag.ProjectID}, new {@class = "btn btn-default"})
    </div>
</div>
<div id="bottom-area">
    <div id="scrum-board">
        <div id="board-left" class="board-area" data-state="0">
            <h3>Not Started</h3>
            @foreach (var item in Model.Where(i => i.State == ProjectBacklogItem.BacklogItemState.NotStarted))
            {
                Html.RenderPartial("_BacklogItemBox", item);
            }
        </div>
        <div id="board-middle" class="board-area" data-state="1">
            <h3>In Progress</h3>
            @foreach (var item in Model.Where(i => i.State == ProjectBacklogItem.BacklogItemState.InProgress))
            {
                Html.RenderPartial("_BacklogItemBox", item);
            }
        </div>
        <div id="board-right" class="board-area" data-state="2">
            <h3>Done</h3>
            @foreach (var item in Model.Where(i => i.State == ProjectBacklogItem.BacklogItemState.Complete))
            {
                Html.RenderPartial("_BacklogItemBox", item);
            }
        </div>
    </div>
</div>

@Html.Partial("_Context_Backlog")

ScrumTool/Views/Project/_Context_Backlog.cshtml
<ul id="contextMenu" class="dropdown-menu" role="menu" style="display:none">
    <li><a tabindex="-1" href="#" class="context-details"><i class="fa fa-folder-o context-menu-icon"></i>Details</a></li>
    <li><a tabindex="-1" href="#" class="context-edit"><i class="fa fa-pencil-square-o context-menu-icon"></i>Edit Item</a></li>
    <li class="divider"></li>
    <li><a tabindex="-1" href="#" class="context-remove-item"><i class="fa fa-times context-menu-icon"></i>Remove Backlog Item</a></li>
</ul>